name: Continous Integration

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: "Build 📦"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install, build, and upload your site output
        uses: withastro/action@v6
        with:
          package-manager: bun@latest
      - name: Check format
        run: bun run format:check

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: "Deploy 🚀"
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
